# Jekyll workshop-template evanwill
# https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

# Notes: 
# - pages with "nav: true" in front matter will be in header nav
# - figure include for centered images, put file in images directory and use: {% include figure.html img="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}

# Site settings
# title appears in the header
title: colorai
# description and keywords for meta tags
description: "The AAAI Workshop on Connecting Low-Rank Representations in AI"
keywords: "AI, ML, deep learning, low-rank, factorization, circuits, tensors, networks"

# author settings for cc-by, appears in the footer
author: antonio vergari
pub_year: 2024
github_username: april-tools

# add the full url for the github repository
repo: "https://github.com/april-tools/colorai"

# site urls
# Optional if using GitHub Pages! If building manually, these must be set correctly.
# When using github pages just leave these blank!
#
# add the url for the domain,
# on gh-pages follow the pattern: https://username.github.io 
url: 
# add subsection of the domain,
# on gh-pages this is a / followed by the name of the repository
baseurl: 

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google-analytics-id: 

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown
